version: '3'

services:
  api:
    container_name: timesheet-backend
    image: timesheet-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    restart: always
