server:
  port: 8081

spring:
  application:
    name: backend-sgsi
  datasource:
    url: jdbc:mysql://147.182.215.248:3306/timesheet_dev?serverTimezone=America/Lima&allowPublicKeyRetrieval=true&useSSL=false
    username: remoto
    password: 1Franklin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 3

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

keycloak:
  realm: afus
  auth-server-url: ${KEYCLOACK_SERVER:http://147.182.215.248:8091/auth}
  ssl-required: NONE
  resource: front-afus
  credentials:
    secret: 24YNGpou7pdmusuVehOmq4H3BlGgxdyV
  use-resource-role-mappings: true
  bearer-only: true
